version: "3.1"
services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nodejs/src
    restart: unless-stopped
    environment:
      POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres
  postgres:
    image: postgres:12.5-alpine
    volumes:
      - .docker/postgres:/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: express
      POSTGRES_HOST_AUTH_METHOD: trust

